<?xml version="1.0"?>
<?xml-model
  href="http://download.ros.org/schema/package_format3.xsd"
  schematypens="http://www.w3.org/2001/XMLSchema"?>

<package format="3">

  <name>desktop_detector</name>

  <version>0.0.1</version>

  <description>
    Real-time desktop object detection on NVIDIA Jetson Orin NX.
    The node runs a trained YOLO model, displays detection results,
    publishes object information through ROS2, and saves experiment results.
  </description>

  <maintainer email="adam@example.com">
    adam
  </maintainer>

  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>

</package>

